server:
  port: 8060

application:
  config:
    stripe-plan-url: http://localhost:8060/api/payment-service/plans
    stripe-customer-url: http://localhost:8060/api/payment-service/customers
    stripe-subscription-url: http://localhost:8060/api/payment-service/subscriptions


spring:
  application:
  name: subscription-service

  jwt:
    jwtExpirationInMs: 1800000
    secret: 36763979244226452948404D635164546A576D5A7134D43777217A25432A462D

  datasource:
    url: jdbc:mysql://localhost:3306/amourlink
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

