#spring:
#  application:
#    name: media-service
#  config:
#    import: optional:configserver:http://config-server:8888

eureka:
  instance:
    hostname: discovery
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

server:
  port: 8080

spring:
  application:
    name: user-service
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  jwt:
    jwtExpirationInMs: 1800000
    secret: 36763979244226452948404D635164546A576D5A7134D43777217A25432A462D
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:mysql://mysql:3306/amourlink
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true

  kafka:
    bootstrap-servers: kafka:29092

application:
  config:
    media-service-url: http://media-service:8070/api/media-service/images
