server:
  port: 8081

spring:
  application:
    name: security-service

  jwt:
    jwtExpirationInMs: 1800000
    secret: 36763979244226452948404D635164546A576D5A7134D43777217A25432A462D

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/amourlink
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


oauth2:
  baseUrl: https://api.github.com/user/emails\

google:
  client:
    client-id: https://902213864397-r88n97ocfudhkgv4vagle3tbmrmve9dc.apps.googleusercontent.com

facebook:
  app:
    id: 970835071296481
    secret: 62075352a1fc4ad0dd6b5ac4fc90b057