spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: zemskiy1255@gmail.com
    password: ijmxkvobqccwsavz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: localhost:9092
